### ISSUE TITLE
Reset textarea height

### ISSUE THREAD

**Issue by aaronrubinstein** [jesseskinner/svelte-autosize#2]
I may be missing something simple here, but I can't figure out how to trigger the height adjustment when programmatically updating or clearing the textarea content. Per the [source docs](http://www.jacklmoore.com/autosize/), I need to call `autosize.update(elements)` or dispatch the `autosize:update` event, however I can't seem to get either of these to work.

[Example REPL](https://svelte.dev/repl/8e5cdc183eb34e4695dae410910d6a66?version=3.55.1)

**Comment by jesseskinner** [comment]
@aaronrubinstein thanks for the issue! I've added `autosize.update` (and `autosize.destroy` too) and released it as v1.1.0.

I had to change three things in your REPL to get it working though:

1. instead of `let ta = document.querySelector('textarea')`, I'm using `bind:this={ta}` on the textarea to get the dom node
2. `autosize.update` didn't use the new value to shrink, so I had to set `ta.style.height = ''` to reset the height before calling `autosize.update(ta)`
3. I had to wait for this to take effect, so I used Svelte's `tick` function for this, but `setTimeout` or `requestAnimationFrame` would work as well.

I though about adding those workarounds into this library itself, but then decided it'd be best to add as little as possible, to match the functionality of the original `autosize`, because these workarounds might be confusing, unexpected, or cause issues for someone else.

Here is a revised, working REPL: https://svelte.dev/repl/ce161698718f49ebb1842e357cef251b?version=3.55.1

I hope that helps!

**Comment by aaronrubinstein** [comment]
This is great, thanks @jesseskinner!

As an alternative to including `ta.style.height = ''`, it looks like I can also make `clearInput` an `async` function and then `await tick()` followed by `autosize.update(ta)`

Example: https://svelte.dev/repl/b449058e859f41989504a678f9f906f1?version=3.55.1

**Comment by jesseskinner** [comment]
@aaronrubinstein oh nice, that's way better. I'll update the README accordingly. Thanks!
